### ISSUE TITLE
Fixing the Mental Health Article button

### ISSUE THREAD

**Issue by YalfamIamShaon** [Hackathon7/Pacify-final#43] opened 2022-03-03 12:53 UTC
First of all great website. But whenever I click on Mental Health Article it does not take me to that section. So @Hackathon7 if you allow me I can fix that and also start my journey as a GSSOC 22 contributor.

**Comment by HarshKumarChoudary** [comment] 2022-03-05 01:29
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me, if the issue is not resolved yet. Thanks.

**Closed** 2022-04-20 16:43 UTC
Labels: good first issue, GSSoC22, Level1
